basic/models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $first_name
 * @property string $last_name
 * @property string $address
 * @property string $email
 * @property string $tax_id
 * @property string $tax_office
 * @property string $phone_number
 * @property string $password
 * @property string $password_reset_token
 * @property string $auth_key
 */
class User extends ActiveRecord implements IdentityInterface
{
	public $full_name;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['email', 'tax_id', 'tax_office', 'phone_number', 'password'], 'required'],
            [['first_name', 'last_name'], 'required', 'message' => Yii::t('app', '{attribute} is required')],
            [['address'], 'required', 'message' => Yii::t('app', '{attribute_f} is required', ['attribute_f' => '{attribute}'])],
	        [['first_name', 'last_name'], 'string', 'max' => 30],
            [['address'], 'string', 'max' => 250],
            [['email', 'tax_id', 'tax_office'], 'string', 'max' => 100],
            [['phone_number'], 'number'],
            [['password'], 'string', 'length' => [8,255]],
	        [['email', 'phone_number'], 'unique'],
	        ['email', 'email'],
        ];
    }

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id'           => 'ID',
			'created_at'   => 'Created At',
			'updated_at'   => 'Updated At',
			'deleted_at'   => 'Deleted At',
			'first_name'   => Yii::t('app','First name'),
			'last_name'    => Yii::t('app','Last name'),
			'address'      => Yii::t('app','Address'),
			'email'        => Yii::t('app','Email'),
			'tax_id'       => Yii::t('app','Tax ID'),
			'tax_office'   => Yii::t('app','Tax office'),
			'phone_number' => Yii::t('app','Phone number'),
			'password'     => Yii::t('app','Password'),
		];
	}

	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			TimestampBehavior::className(),
		];
	}

	/**
	 * Get user's full name
	 *
	 * @return string
	 */
	public function getFullName()
	{
		return $this->first_name . ' ' . $this->last_name;
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getBankDetails()
	{
		return $this->hasMany(BankDetails::className(), ['user_id' => 'id']);
	}

	/**
	 * @inheritdoc
	 */
	public static function findIdentity($id)
	{
		return static::findOne(['id' => $id, 'deleted_at' => null]);
	}
	/**
	 * @inheritdoc
	 */
	public static function findIdentityByAccessToken($token, $type = null)
	{
		throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
	}
	/**
	 * Finds user by username
	 *
	 * @param string $email
	 * @return static|null
	 */
	public static function findByEmail($email)
	{
		return static::findOne(['email' => $email, 'deleted_at' => null]);
	}
	/**
	 * Finds user by password reset token
	 *
	 * @param string $token password reset token
	 * @return static|null
	 */
	public static function findByPasswordResetToken($token)
	{
		if (!static::isPasswordResetTokenValid($token)) {
			return null;
		}
		return static::findOne([
			'password_reset_token' => $token,
			'deleted_at' => null,
		]);
	}
	/**
	 * Finds out if password reset token is valid
	 *
	 * @param string $token password reset token
	 * @return bool
	 */
	public static function isPasswordResetTokenValid($token)
	{
		if (empty($token)) {
			return false;
		}
		$timestamp = (int) substr($token, strrpos($token, '_') + 1);
		$expire = Yii::$app->params['user.passwordResetTokenExpire'];
		return $timestamp + $expire >= time();
	}
	/**
	 * @inheritdoc
	 */
	public function getId()
	{
		return $this->getPrimaryKey();
	}
	/**
	 * @inheritdoc
	 */
	public function getAuthKey()
	{
		return $this->auth_key;
	}
	/**
	 * @inheritdoc
	 */
	public function validateAuthKey($authKey)
	{
		return $this->getAuthKey() === $authKey;
	}
	/**
	 * Validates password
	 *
	 * @param string $password password to validate
	 * @return bool if password provided is valid for current user
	 */
	public function validatePassword($password)
	{
		return Yii::$app->security->validatePassword($password, $this->password);
	}

	/**
	 * Generates password hash from password and sets it to the model
	 *
	 * @param string $password
	 *
	 * @throws \yii\base\Exception
	 */
	public function setPassword($password)
	{
		$this->password = Yii::$app->security->generatePasswordHash($password);
	}
	/**
	 * Generates "remember me" authentication key
	 */
	public function generateAuthKey()
	{
		$this->auth_key = Yii::$app->security->generateRandomString();
	}
	/**
	 * Generates new password reset token
	 */
	public function generatePasswordResetToken()
	{
		$this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
	}
	/**
	 * Removes password reset token
	 */
	public function removePasswordResetToken()
	{
		$this->password_reset_token = null;
	}
}

basic/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\BankDetails;
use app\models\InvoiceForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Cookie;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{
	public function beforeAction($action)
	{
		if (!parent::beforeAction($action)) {
			return false;
		}
		$cookies = Yii::$app->request->cookies;
		// get the "language" cookie value. If the cookie does not exist, return "en" as the default value.
		$locale = $cookies->getValue('locale', 'en');
		Yii::$app->language = $locale;

		return true;
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'generate-invoice'],
                'rules' => [
                    [
                        'actions' => ['logout', 'generate-invoice'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                /*'actions' => [
                    'logout' => ['post'],
                ],*/
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

	/**
	 * Register action
	 *
	 * @return string|Response
	 * @throws \yii\base\Exception
	 */
	public function actionRegister()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new User();
		$bankDetailsModel = new BankDetails();
		if ($model->load(Yii::$app->request->post()) && $bankDetailsModel->load(Yii::$app->request->post())) {
			$isValid = $model->validate();
			$isValid = $bankDetailsModel->validate() && $isValid;
			if ($isValid) {
				// Let's encrypt password
				$model->setPassword($model->password);
				$model->save();
				$model->refresh();

				$bankDetailsModel->user_id = $model->id;
				$bankDetailsModel->save();
				Yii::$app->getSession()->setFlash( 'registration_success', "You have been registered successfully!");
				return $this->goHome();
			}
		}

		return $this->render('register', [
			'model' => $model,
			'bankDetailsModel' => $bankDetailsModel
		]);
	}

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

	/**
	 * Language switcher action
	 *
	 * @param $locale string Language code (IS0-639-1)
	 *
	 * @see https://en.wikipedia.org/wiki/ISO_639-1 List of available codes
	 *
	 * @return Response
	 */
	public function actionLanguage($locale)
	{
		$allowedLanguages = ['en', 'bs'];

		if (!in_array($locale, $allowedLanguages)) {
			$locale = 'en';
		}

		Yii::$app->language = $locale;

		$languageCookie = new Cookie([
			'name' => 'locale',
			'value' => $locale,
			'expire' => time() + 60 * 60 * 24 * 30, // 30 days
		]);
		Yii::$app->response->cookies->add($languageCookie);

		return $this->goBack();
    }

	public function actionGenerateInvoice()
	{
		$model = new InvoiceForm();
		return $this->render('generate-invoice',[
			'model' => $model
		]);
    }
}

basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

basic/views/site/generate-invoice.php
<?php
/**
 * @author: Marko Mikulic
 */

use dosamigos\tinymce\TinyMce;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Generate invoice');

$user = Yii::$app->user->identity;
$userBankDetails = $user->getBankDetails()->one();
?>
<div class="container">

	<div class="row">
		<?php
		$form = ActiveForm::begin([
            'id' => 'invoice-form',
            'action' => ['/invoice/view'],
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-4\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-2 control-label text-left'],
            ],
        ]); ?>

        <div class="col-md-12 text-center">
           <h2>NAME</h2>
        </div>

		<div class="col-md-6">
			<?= $form->field($model, 'toCompany')->textInput(['autofocus' => true]) ?>
			<?= $form->field($model, 'address')->textInput() ?>
			<?= $form->field($model, 'invoice_number')->textInput() ?>
			<?= $form->field($model, 'invoice_date')->widget(\yii\jui\DatePicker::className(), [
				'language' => Yii::$app->language,
				'dateFormat' => 'dd-MM-yyyy',
				'options' => ['class' => 'form-control']
			]) ?>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label class="col-lg-2 control-label text-left">From:</label>
                <div class="col-lg-6"><span class="form-control"><?= $user->fullName ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'Address') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $user->address ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'Phone') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $user->phone_number ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'Email') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $user->email ?></span></div>
            </div>

            <br>
            <br>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'Tax ID') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $user->tax_id ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'Tax office') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $user->tax_office ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'Bank') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $userBankDetails->bank ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'Account owner') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $user->fullName ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'IBAN') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $userBankDetails->iban ?></span></div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label text-left"><?= Yii::t('app', 'SWIFT') ?>:</label>
                <div class="col-lg-6"><span class="form-control"><?= $userBankDetails->swift ?></span></div>
            </div>
        </div>


        <div class="col-md-12">
            <h2 class="text-center text-uppercase"><?= Yii::t('app', 'Invoice') ?></h2>
        </div>

		<?= $form->field($model, 'invoice', [
			'template' => "{label}\n<div class=\"col-lg-12\">{input}</div>\n<div class=\"col-lg-12\">{error}</div>",
			'labelOptions' => ['class' => 'col-lg-1 control-label text-left'],
		])->widget(TinyMce::className(), [
			'options' => ['rows' => 12],
			'language' => Yii::$app->language,
			'clientOptions' => [
				'plugins' => [
					"advlist autolink lists link charmap print preview anchor",
					"searchreplace visualblocks code fullscreen",
					"insertdatetime media table contextmenu paste image"
				],
				'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
			]
		]);?>


		<div class="form-group">
			<div class="col-lg-offset-1 col-lg-11">
				<?= Html::submitButton(Yii::t('app', 'Create invoice'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
			</div>
		</div>


		<?php ActiveForm::end(); ?>
	</div>

</div>

basic/views/site/index.php
<?php

/* @var $this yii\web\View */

use app\components\Greeter;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Home');
?>
<div class="site-index">

    <div class="jumbotron">

        <h1>
            <?php
            if (Yii::$app->user->isGuest) {
                echo Yii::t('app', 'Welcome to ') . Yii::$app->name;
            } else {
	            echo Greeter::getGreetingMessage();
            }
            ?>
        </h1>
    </div>

    <div class="body-content">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 text-center">
                    <h2><?= Yii::t('app', 'Register') ?></h2>
                    <p>
                        <?= Html::a(Yii::t('app', 'Register'), ['/site/register'], ['class' => 'btn btn-default']) ?>
                    </p>
                </div>
                <div class="col-lg-6 text-center">
                    <h2><?= Yii::t('app', 'Login') ?></h2>
                    <p>
		                <?= Html::a(Yii::t('app', 'Login'), ['/site/login'], ['class' => 'btn btn-default']) ?>
                    </p>
                </div>
            </div>
        </div>

    </div>
</div>

basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app','Login');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'Please fill out the following fields to login') ?>:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-4\">{input}</div>\n<div class=\"col-lg-6\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

basic/views/site/register.php
<?php
/**
 * @author: Marko Mikulic
 */
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
/* @var $bankDetailsModel \app\models\BankDetails */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Register');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'Please fill out the following fields to register') ?>:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-4\">{input}</div>\n<div class=\"col-lg-6\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
    ]); ?>

        <?= $form->field( $model, 'first_name' )->textInput( [ 'autofocus' => true ] ) ?>
        <?= $form->field( $model, 'last_name' )->textInput() ?>
        <?= $form->field( $model, 'email' )->textInput() ?>
        <?= $form->field( $model, 'address' )->textInput() ?>
        <?= $form->field( $model, 'tax_id' )->textInput() ?>
        <?= $form->field( $model, 'tax_office' )->textInput() ?>
        <?= $form->field( $model, 'phone_number' )->textInput() ?>
        <?= $form->field( $bankDetailsModel, 'bank' )->textInput() ?>
        <?= $form->field( $bankDetailsModel, 'swift' )->textInput() ?>
        <?= $form->field( $bankDetailsModel, 'iban' )->textInput() ?>
        <?= $form->field( $model, 'password' )->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app', 'Register'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>