basic/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\BankDetails;
use app\models\InvoiceForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Cookie;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{
	public function beforeAction($action)
	{
		if (!parent::beforeAction($action)) {
			return false;
		}
		$cookies = Yii::$app->request->cookies;
		// get the "language" cookie value. If the cookie does not exist, return "en" as the default value.
		$locale = $cookies->getValue('locale', 'en');
		Yii::$app->language = $locale;

		return true;
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'generate-invoice'],
                'rules' => [
                    [
                        'actions' => ['logout', 'generate-invoice'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                /*'actions' => [
                    'logout' => ['post'],
                ],*/
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

	/**
	 * Register action
	 *
	 * @return string|Response
	 * @throws \yii\base\Exception
	 */
	public function actionRegister()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new User();
		$bankDetailsModel = new BankDetails();
		if ($model->load(Yii::$app->request->post()) && $bankDetailsModel->load(Yii::$app->request->post())) {
			$isValid = $model->validate();
			$isValid = $bankDetailsModel->validate() && $isValid;
			if ($isValid) {
				// Let's encrypt password
				$model->setPassword($model->password);
				$model->save();
				$model->refresh();

				$bankDetailsModel->user_id = $model->id;
				$bankDetailsModel->save();
				Yii::$app->getSession()->setFlash( 'registration_success', "You have been registered successfully!");
				return $this->goHome();
			}
		}

		return $this->render('register', [
			'model' => $model,
			'bankDetailsModel' => $bankDetailsModel
		]);
	}

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

	/**
	 * Language switcher action
	 *
	 * @param $locale string Language code (IS0-639-1)
	 *
	 * @see https://en.wikipedia.org/wiki/ISO_639-1 List of available codes
	 *
	 * @return Response
	 */
	public function actionLanguage($locale)
	{
		$allowedLanguages = ['en', 'bs'];

		if (!in_array($locale, $allowedLanguages)) {
			$locale = 'en';
		}

		Yii::$app->language = $locale;

		$languageCookie = new Cookie([
			'name' => 'locale',
			'value' => $locale,
			'expire' => time() + 60 * 60 * 24 * 30, // 30 days
		]);
		Yii::$app->response->cookies->add($languageCookie);

		return $this->goBack();
    }

	public function actionGenerateInvoice()
	{
		$model = new InvoiceForm();
		return $this->render('generate-invoice',[
			'model' => $model
		]);
    }
}

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\components\Greeter;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) . ' - ' . Yii::$app->name ?></title>
    <?php $this->head() ?>
</head>
<body class="Site">
<?php $this->beginBody() ?>

<div class="wrap Site-content">
    <?php
    $isGuest = Yii::$app->user->isGuest;

    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            // Unauthorized links
	        ['label' => Yii::t('app', 'Register'), 'url' => ['/site/register'], 'visible' => $isGuest],
            ['label' => Yii::t('app','Login'), 'url' => ['/site/login'], 'visible' => $isGuest],
	        // Authorized links
            ['label' => ( !$isGuest ) ? Greeter::getGreetingMessage() : null, 'visible' => ! $isGuest],
            ['label' => Yii::t('app','Generate invoice'), 'url' => ['/site/generate-invoice'], 'visible' => ! $isGuest],
            ['label' => Yii::t('app','Logout'), 'url' => ['/site/logout'], 'visible' => ! $isGuest],
            ['label' => Yii::t('app', 'Language'), 'items' => [
	            ['label' => 'ENG', 'url' => ['/site/language', 'locale' => 'en']],
                ['label' => 'BHS', 'url' => ['/site/language', 'locale' => 'bs']],
            ]]
        ],
    ]);
    NavBar::end();
    ?>


    <?php
    $currentRoute = Yii::$app->controller->action->id;
    $containerClass = ($currentRoute == 'index') ? ' background-img h-100p' : '';
    ?>

    <div class="container full-width <?= $containerClass ?>">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container text-center">
        <p>Copyright <?= Yii::$app->name . ' ' . date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>